- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    windows:
      - version: 10
        edition: Windows 10 Enterprise Evaluation
      - version: 2012r2
        edition: Windows Server 2012 R2 SERVERSTANDARD
      - version: 2016
        edition: Windows Server 2016 SERVERSTANDARD
  tasks:
    - name: Ensuring ../http Folder Exists
      file:
        path: ../http
        state: directory

    - name: Ensuring ../http Distro Folders Exist
      file:
        path: "../http/{{ item }}"
        state: directory
      with_items:
        - centos
        - debian
        - ubuntu

    - name: Ensuring ../answer_files Folder Exists
      file:
        path: ../answer_files
        state: directory

    - name: Ensuring ../answer_files For Windows Versions Folders Exist
      file:
        path: "../answer_files/{{ item['version'] }}"
        state: directory
      with_items: "{{ windows }}"

    - name: Generating Kickstart Configuration
      template:
        src: templates/ks.cfg.j2
        dest: ../http/centos/ks.cfg

    - name: Generating Ubuntu Preseed Configuration
      template:
        src: templates/ubuntu_preseed.cfg.j2
        dest: ../http/ubuntu/preseed.cfg

    - name: Generating Debian Preseed Configuration
      template:
        src: templates/debian_preseed.cfg.j2
        dest: ../http/debian/preseed.cfg

    - name: Generating Windows Autounattend Configurations
      template:
        src: "templates/Autounattend.xml.j2"
        dest: "../answer_files/{{ item['version'] }}/Autounattend.xml"
      with_items: "{{ windows }}"

    - name: Generating Packer Variables
      template:
        src: templates/variables.json.j2
        dest: ../variables.json

    - name: Generating Packer Private Variables
      template:
        src: templates/private_variables.json.j2
        dest: ../private_variables.json

    - name: Generating PowerCLI Script
      template:
        src: templates/GuestIPHack.ps1.j2
        dest: ../GuestIPHack.ps1
