- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Ensuring ../http Folder Exists
      file:
        path: ../http
        state: directory

    - name: Ensuring ../http Distro Folders Exist
      file:
        path: "../http/{{ item }}"
        state: directory
      with_items:
        - centos
        - debian
        - ubuntu
        - windows/2016

    - name: Generating Kickstart Configuration
      template:
        src: templates/ks.cfg.j2
        dest: ../http/centos/ks.cfg

    - name: Generating Ubuntu Preseed Configuration
      template:
        src: templates/ubuntu_preseed.cfg.j2
        dest: ../http/ubuntu/preseed.cfg

    - name: Generating Debian Preseed Configuration
      template:
        src: templates/debian_preseed.cfg.j2
        dest: ../http/debian/preseed.cfg

    - name: Generating Windows 2016 Autounattend Configuration
      template:
        src: templates/Autounattend_2016.xml.j2
        dest: ../http/windows/2016/Autounattend.xml

    - name: Generating Packer Variables
      template:
        src: templates/variables.json.j2
        dest: ../variables.json

    - name: Generating Packer Private Variables
      template:
        src: templates/private_variables.json.j2
        dest: ../private_variables.json

    - name: Generating PowerCLI Script
      template:
        src: templates/GuestIPHack.ps1.j2
        dest: ../GuestIPHack.ps1
